import localFont from "next/font/local";
import "./globals.css";

const FFDinProblack = localFont({
  src: "./fonts/FFDinPro-Black.ttf",
  variable: "--font-FFDinPro-Black",
  weight: "100 900",
});

const FFDinProReg = localFont({
  src: "./fonts/FFDinPro-Regular.ttf",
  variable: "--font-FFDinPro-Regular",
  weight: "100 900",
});

export const metadata = {
  title: "War Room Voucher",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${FFDinProReg.variable} ${FFDinProblack.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}